from __future__ import annotations

from typing import Dict

AURA_STEP = 400

DEFAULT_STRINGS: Dict[str, str] = {
    "window_title": "Bout Review",
    "score_tracker_title": "Score Tracker",
    "score_left_label": "Left",
    "score_right_label": "Right",
    "score_label": "Score",
    "score_enable": "Enable Score",
    "score_point_left": "Point Left",
    "score_point_right": "Point Right",
    "score_no_point": "No Point (Simul / Off target)",
    "button_remove_video": "Remove video",
    "button_import_videos": "Import videos",
    "label_segments": "Segments ({mark_in_key} = Mark In, {mark_out_key} = Mark Out)",
    "mark_indicator_on": "Mark In: ON",
    "mark_indicator_off": "Mark In: OFF",
    "button_edit_segment": "Edit segment",
    "button_delete_segment": "Delete segment",
    "button_duplicate_segment": "Duplicate segment",
    "label_notes": "Notes",
    "button_edit_note": "Edit note",
    "button_delete_note": "Delete note",
    "label_videos": "Videos",
    "label_gap_speed": "Gap speed (export):",
    "action_new_project": "New Project",
    "action_open_project": "Open Project",
    "action_import_videos": "Import Videos",
    "action_export": "Export",
    "action_open_exports": "Open Exports Folder",
    "action_play_pause": "Play/Pause",
    "action_mute_audio": "Mute Audio",
    "action_unmute_audio": "Unmute Audio",
    "action_mark_in": "Mark In",
    "action_mark_out": "Mark Out",
    "action_add_comment": "Add Comment",
    "action_add_chapter": "Add Chapter",
    "action_score_tracker": "Score Tracker",
    "action_scrub_back": "Scrub Back",
    "action_scrub_forward": "Scrub Forward",
    "action_scrub_frame_back": "Step Frame Back",
    "action_scrub_frame_forward": "Step Frame Forward",
    "action_open_config": "Open config",
    "dialog_choose_project_dir": "Choose or create project folder",
    "dialog_open_project_dir": "Open project folder",
    "dialog_import_videos": "Import video files",
    "dialog_folder_not_empty_title": "Folder not empty",
    "dialog_folder_not_empty_msg": "'{name}' is not empty. Create project here anyway?",
    "dialog_create_project_failed_title": "Create project failed",
    "dialog_open_project_failed_title": "Open project failed",
    "dialog_no_project_title": "No project",
    "dialog_no_project_msg": "Create or open a project first.",
    "dialog_no_project_msg_alt": "Open or create a project first.",
    "dialog_import_failed_title": "Import failed",
    "dialog_no_video_title": "No video",
    "dialog_no_video_msg": "Import and select a video to continue.",
    "dialog_no_video_remove_msg": "Select a video to remove.",
    "dialog_no_mark_in_title": "No mark in",
    "dialog_no_mark_in_msg": "Press I to set a start before marking out.",
    "dialog_invalid_segment_title": "Invalid segment",
    "dialog_invalid_segment_msg": "End must be after start.",
    "dialog_remove_video_title": "Remove video",
    "dialog_remove_video_msg": "Remove this video from the project? All segments and notes tied to it will be deleted.",
    "dialog_no_segment_title": "No segment",
    "dialog_no_segment_msg": "Select a segment to {action}.",
    "dialog_invalid_segment_duration_msg": "End time exceeds media duration.",
    "dialog_no_note_title": "No note",
    "dialog_no_note_msg": "Select a note to {action}.",
    "dialog_no_segments_title": "No segments",
    "dialog_no_segments_msg": "Mark keep ranges before exporting.",
    "dialog_chapter_warnings_title": "Chapter warnings",
    "dialog_chapter_warnings_header": "Chapters do not meet YouTube requirements:",
    "dialog_chapter_warnings_continue": "Continue export anyway?",
    "dialog_export_progress_label": "Exporting...",
    "dialog_export_progress_cancel": "Cancel",
    "dialog_export_complete_title": "Export complete",
    "dialog_export_cancelled_title": "Export cancelled",
    "dialog_export_cancelled_msg": "Export was cancelled.",
    "dialog_export_failed_title": "Export failed",
    "dialog_open_config_failed_title": "Config file error",
    "dialog_open_config_failed_msg": "Couldn't open config at {path}.",
    "dialog_edit_segment_title": "Edit segment",
    "dialog_duplicate_segment_title": "Duplicate segment",
    "segment_form_start": "Start (s)",
    "segment_form_end": "End (s)",
    "segment_form_label": "Label",
    "segment_form_speed": "Speed",
    "note_form_timestamp": "Timestamp (s)",
    "note_form_type": "Type",
    "note_form_text": "Text",
    "note_text_prompt": "Note text:",
    "note_new_title": "New {note_type}",
    "note_edit_title": "Edit note",
    "status_project_created": "Project created at {directory}",
    "status_project_opened": "Project opened from {directory}",
    "status_imported_videos": "Imported {count} video(s)",
    "status_loaded_media": "Loaded {filename}",
    "status_audio_muted": "Audio muted",
    "status_audio_unmuted": "Audio unmuted",
    "status_marked_in": "Marked in at {time:.2f}s",
    "status_segment_saved": "Segment {label} saved",
    "status_video_removed": "Video removed",
    "status_segment_updated": "Segment updated",
    "status_segment_deleted": "Segment deleted",
    "status_segment_duplicated": "Segment duplicated",
    "status_comment_added": "Comment added",
    "status_chapter_added": "Chapter added",
    "status_note_updated": "Note updated",
    "status_note_deleted": "Note deleted",
    "status_gap_ff_on": "Gaps will be fast-forwarded at {speed}x in export.",
    "status_gap_ff_off": "Gap fast-forward is off for export.",
    "gap_ff_button_text": "Fast-forward gaps (export): {state}  ({speed}x)",
    "gap_state_on": "ON",
    "gap_state_off": "OFF",
    "instructions_header": "Quick guide:",
    "instructions_new_open": "- New/Open project: {new_key} / {open_key}",
    "instructions_import": "- Import videos: {import_key} (drag to reorder in the list)",
    "instructions_play_mute": "- Play/Pause: {play_key} • Mute: {mute_key}",
    "instructions_gap_ff": "- Export fast-forward: button under the video to include gaps at a faster speed in highlights.",
    "instructions_scrub": "- Scrub: {back_key} / {fwd_key} ({seconds_step}s)",
    "instructions_frame_step": "- Frame step: {back_key} / {fwd_key} ({frames_step} frame)",
    "instructions_mark": "- Mark In/Out: {in_key} / {out_key}",
    "instructions_add_note": "- Add Comment/Chapter: {comment_key} / {chapter_key}",
    "instructions_score_tracker": "- Score tracker: {score_key} or toolbar button for quick point comments (+ optional auto score).",
    "instructions_double_click": "- Double-click a segment to jump to its start; use Edit/Delete buttons for segments and notes.",
    "instructions_open_exports": "- Open exports folder: {open_exports_key}",
    "instructions_open_config": "- Open config: toolbar button",
    "instructions_export": "- Export: {export_key}",
    "tooltip_new_project": "Create a new project",
    "tooltip_open_project": "Open an existing project",
    "tooltip_import_videos": "Import video files into the project",
    "tooltip_export": "Export highlights and text files",
    "tooltip_open_exports": "Open the project exports folder",
    "tooltip_play_pause": "Play or pause the current video",
    "tooltip_mute_audio": "Toggle audio mute",
    "tooltip_mark_in": "Set segment start (Mark In)",
    "tooltip_mark_out": "Set segment end (Mark Out)",
    "tooltip_add_comment": "Add a comment note at the playhead",
    "tooltip_add_chapter": "Add a chapter note at the playhead",
    "tooltip_score_tracker": "Open score tracker window for quick point comments",
    "tooltip_scrub_back": "Scrub backward by seconds",
    "tooltip_scrub_forward": "Scrub forward by seconds",
    "tooltip_scrub_frame_back": "Step backward by frames",
    "tooltip_scrub_frame_forward": "Step forward by frames",
    "tooltip_open_config": "Open the config file",
    "score_suffix": " (L {left} - {right} R)",
    "quick_point_left": "Point Left{suffix}",
    "quick_point_right": "Point Right{suffix}",
    "quick_no_point": "No Point (Simul / Off target){suffix}",
    "note_type_comment": "comment",
    "note_type_chapter": "chapter",
    "marker_comment_default": "Comment",
    "marker_chapter_default": "Chapter",
    "export_summary_highlights": "Highlights: {path}",
    "export_summary_chapters": "Chapters: {path}",
    "export_summary_comments": "Comments: {path}",
    "export_summary_clips": "Clips: {count} saved",
    "export_summary_gap": "Gaps fast-forwarded at {speed}x.",
    "export_summary_warnings": "Chapter warnings:",
}

GENZ_STRINGS: Dict[str, str] = {
    "window_title": "Bout Review",
    "score_tracker_title": "Aura Tracker",
    "score_left_label": "Left",
    "score_right_label": "Right",
    "score_label": "Aura",
    "score_enable": "Auto aura",
    "score_point_left": "Left aura +{step}",
    "score_point_right": "Right aura +{step}",
    "score_no_point": "No aura (simul / off-target)",
    "button_remove_video": "Yeet vid",
    "button_import_videos": "Drop vids",
    "label_segments": "Clips ({mark_in_key} = Tag In, {mark_out_key} = Tag Out)",
    "mark_indicator_on": "Tag In: LIVE",
    "mark_indicator_off": "Tag In: CHILL",
    "button_edit_segment": "Edit clip",
    "button_delete_segment": "Nuke clip",
    "button_duplicate_segment": "Dupe clip",
    "label_notes": "Vibes",
    "button_edit_note": "Edit vibe",
    "button_delete_note": "Nuke vibe",
    "label_videos": "Vids",
    "label_gap_speed": "Gap zoom (export):",
    "action_new_project": "New proj",
    "action_open_project": "Open proj",
    "action_import_videos": "Import vids",
    "action_export": "Export",
    "action_open_exports": "Open exports stash",
    "action_play_pause": "Play/Chill",
    "action_mute_audio": "Mute sound",
    "action_unmute_audio": "Unmute sound",
    "action_mark_in": "Tag In",
    "action_mark_out": "Tag Out",
    "action_add_comment": "Add vibe",
    "action_add_chapter": "Add chapter",
    "action_score_tracker": "Aura Tracker",
    "action_scrub_back": "Scrub back",
    "action_scrub_forward": "Scrub forward",
    "action_scrub_frame_back": "Frame back",
    "action_scrub_frame_forward": "Frame forward",
    "action_open_config": "Open config",
    "dialog_choose_project_dir": "Pick or make a proj folder",
    "dialog_open_project_dir": "Open proj folder",
    "dialog_import_videos": "Import vid files",
    "dialog_folder_not_empty_title": "Folder's not empty",
    "dialog_folder_not_empty_msg": "'{name}' ain't empty. Make the proj here anyway?",
    "dialog_create_project_failed_title": "Proj creation L",
    "dialog_open_project_failed_title": "Proj open L",
    "dialog_no_project_title": "No proj",
    "dialog_no_project_msg": "Make or open a proj first.",
    "dialog_no_project_msg_alt": "Make or open a proj first.",
    "dialog_import_failed_title": "Import L",
    "dialog_no_video_title": "No vid",
    "dialog_no_video_msg": "Import and pick a vid to keep going.",
    "dialog_no_video_remove_msg": "Pick a vid to yeet.",
    "dialog_no_mark_in_title": "No tag in",
    "dialog_no_mark_in_msg": "Hit I to tag the start before tagging out.",
    "dialog_invalid_segment_title": "Bad clip",
    "dialog_invalid_segment_msg": "End's gotta be after start.",
    "dialog_remove_video_title": "Yeet vid",
    "dialog_remove_video_msg": "Yeet this vid from the proj? All clips and vibes tied to it get nuked.",
    "dialog_no_segment_title": "No clip",
    "dialog_no_segment_msg": "Pick a clip to {action}.",
    "dialog_invalid_segment_duration_msg": "End time goes past the vid length.",
    "dialog_no_note_title": "No vibe",
    "dialog_no_note_msg": "Pick a vibe to {action}.",
    "dialog_no_segments_title": "No clips",
    "dialog_no_segments_msg": "Tag keep ranges before export.",
    "dialog_chapter_warnings_title": "Chapter heads-up",
    "dialog_chapter_warnings_header": "Chapters don't meet YouTube rules:",
    "dialog_chapter_warnings_continue": "Export anyway?",
    "dialog_export_progress_label": "Exporting... hold up",
    "dialog_export_progress_cancel": "Nvm",
    "dialog_export_complete_title": "Export W",
    "dialog_export_cancelled_title": "Export noped",
    "dialog_export_cancelled_msg": "Export got noped.",
    "dialog_export_failed_title": "Export L",
    "dialog_open_config_failed_title": "Config file L",
    "dialog_open_config_failed_msg": "Couldn't open config at {path}.",
    "dialog_edit_segment_title": "Edit clip",
    "dialog_duplicate_segment_title": "Dupe clip",
    "segment_form_start": "Start (sec)",
    "segment_form_end": "End (sec)",
    "segment_form_label": "Tag",
    "segment_form_speed": "Speed",
    "note_form_timestamp": "Time stamp (sec)",
    "note_form_type": "Vibe type",
    "note_form_text": "Text",
    "note_text_prompt": "Drop the text:",
    "note_new_title": "New {note_type}",
    "note_edit_title": "Edit vibe",
    "status_project_created": "Proj spawned at {directory}",
    "status_project_opened": "Proj pulled from {directory}",
    "status_imported_videos": "Pulled {count} vid(s)",
    "status_loaded_media": "{filename} loaded",
    "status_audio_muted": "Audio muted (shhh)",
    "status_audio_unmuted": "Audio back on",
    "status_marked_in": "Tagged in at {time:.2f}s",
    "status_segment_saved": "Clip {label} saved",
    "status_video_removed": "Vid yeeted",
    "status_segment_updated": "Clip updated",
    "status_segment_deleted": "Clip deleted",
    "status_segment_duplicated": "Clip duped",
    "status_comment_added": "Vibe added",
    "status_chapter_added": "Chapter added",
    "status_note_updated": "Vibe updated",
    "status_note_deleted": "Vibe deleted",
    "status_gap_ff_on": "Gaps will zoom at {speed}x on export.",
    "status_gap_ff_off": "Gap zoom is off for export.",
    "gap_ff_button_text": "Gap zoom (export): {state}  ({speed}x)",
    "gap_state_on": "LIVE",
    "gap_state_off": "CHILL",
    "instructions_header": "Speedrun guide:",
    "instructions_new_open": "- New/Open proj: {new_key} / {open_key}",
    "instructions_import": "- Drop vids: {import_key} (drag to reorder the list)",
    "instructions_play_mute": "- Play/Chill: {play_key} • Mute: {mute_key}",
    "instructions_gap_ff": "- Gap zoom: button under the vid to include gaps at faster speed in highlights.",
    "instructions_scrub": "- Scrub: {back_key} / {fwd_key} ({seconds_step}s)",
    "instructions_frame_step": "- Frame step: {back_key} / {fwd_key} ({frames_step} frame)",
    "instructions_mark": "- Tag In/Out: {in_key} / {out_key}",
    "instructions_add_note": "- Add Vibe/Chapter: {comment_key} / {chapter_key}",
    "instructions_score_tracker": "- Aura tracker: {score_key} or toolbar button for quick aura notes (+ optional auto aura).",
    "instructions_double_click": "- Double-click a clip to jump to start; use Edit/Delete for clips and vibes.",
    "instructions_open_exports": "- Open exports folder: {open_exports_key}",
    "instructions_open_config": "- Open config: toolbar button",
    "instructions_export": "- Export: {export_key}",
    "tooltip_new_project": "Spin up a new proj",
    "tooltip_open_project": "Open an existing proj",
    "tooltip_import_videos": "Drop vids into the proj",
    "tooltip_export": "Export highlights + text files",
    "tooltip_open_exports": "Open the exports stash",
    "tooltip_play_pause": "Play or chill the current vid",
    "tooltip_mute_audio": "Toggle mute",
    "tooltip_mark_in": "Tag in (clip start)",
    "tooltip_mark_out": "Tag out (clip end)",
    "tooltip_add_comment": "Add a vibe at the playhead",
    "tooltip_add_chapter": "Add a chapter at the playhead",
    "tooltip_score_tracker": "Open Aura Tracker for quick aura notes",
    "tooltip_scrub_back": "Scrub back by seconds",
    "tooltip_scrub_forward": "Scrub forward by seconds",
    "tooltip_scrub_frame_back": "Step back by frames",
    "tooltip_scrub_frame_forward": "Step forward by frames",
    "tooltip_open_config": "Open the config file",
    "score_suffix": " (L {left} aura / R {right} aura)",
    "quick_point_left": "Left aura +{step}{suffix}",
    "quick_point_right": "Right aura +{step}{suffix}",
    "quick_no_point": "No aura (simul / off-target){suffix}",
    "note_type_comment": "vibe",
    "note_type_chapter": "chapter",
    "marker_comment_default": "Vibe",
    "marker_chapter_default": "Chapter",
    "export_summary_highlights": "Highlights: {path}",
    "export_summary_chapters": "Chapters: {path}",
    "export_summary_comments": "Vibes: {path}",
    "export_summary_clips": "Clips: {count} saved",
    "export_summary_gap": "Gaps zoomed at {speed}x.",
    "export_summary_warnings": "Chapter heads-up:",
}

NOTE_TYPE_LABELS = {"comment": "vibe", "chapter": "chapter"}

WARNING_MAP = {
    "YouTube requires at least 3 chapter timestamps.": "YouTube wants at least 3 chapter stamps.",
    "Some chapters are less than 10 seconds apart.": "Some chapters are under 10s apart.",
    "Last chapter is within 10 seconds of the end.": "Last chapter is within 10s of the end.",
}


def ui_text(gen_z: bool, key: str, **kwargs) -> str:
    source = GENZ_STRINGS if gen_z else DEFAULT_STRINGS
    text = source.get(key) or DEFAULT_STRINGS.get(key, key)
    if not kwargs:
        return text
    try:
        return text.format(**kwargs)
    except (KeyError, ValueError):
        return text


def note_type_label(gen_z: bool, note_type: str) -> str:
    if not gen_z:
        return note_type
    return NOTE_TYPE_LABELS.get(note_type, note_type)
